import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { colorPalettes, projects, tasks, users } from "./schema";
//import * as schema from "./schema";

// Connection to the SQLite Database, creating a client object with the URL to the database file
const client = createClient({
  url: "file:db/dev.db",
});

// Creating a drizzle object from the client object which we need to apply the migrations (generated by Drizzle Kit) to the connected database

const db = drizzle(client);

const createUser = async () => {
  await db
    .insert(users)
    .values({ id: 1, createdAt: "2023-07-10 17:45:34" })
    .returning()
    .all();
};

createUser();

const createColorPalettes = async () => {
  await db
    .insert(colorPalettes)
    .values([
      {
        colors:
          '{"color1":"hsl(298, 29%, 43%)","color2":"hsl(179, 39%, 54%)","color3":"hsl(28, 77%, 56%)"}',
        createdAt: "2023-07-10 17:45:34",
      },
    ])
    .returning()
    .all();
};

createColorPalettes();

const createProjectsWithTasks = async () => {
  const insertedProjects = await db
    .insert(projects)
    .values([
      {
        name: "Wood Art",
        description: "Colorful japanese wood block art",
        userId: 1,
        createdAt: "2023-07-11 18:00:00",
        colorPaletteId: 1,
      },
      {
        name: "Fabric Art Piece",
        description: "Japanese inspired Linen Fabric Art",
        userId: 1,
        createdAt: "2023-07-11 19:00:00",
        colorPaletteId: 1,
      },
      {
        name: "Arched Shelving",
        description: "Mediterranean inspired shelving with arched frame",
        userId: 1,
        createdAt: "2023-07-11 20:00:00",
        colorPaletteId: 1,
      },
    ])
    .returning()
    .all();

  const insertedTasks = await db
    .insert(tasks)
    .values([
      {
        description: "Decide on wood arrangement",
        projectId: insertedProjects[0].id,
        createdAt: "2023-07-12 17:45:00",
        completedAt: "2023-07-13 17:45:00",
        isCompleted: 1,
      },
      {
        description: "wood",
        type: "material",
        createdAt: "2023-07-12 17:45:00",
        projectId: insertedProjects[0].id,
      },
      {
        description: "cut wood",
        createdAt: "2023-07-12 17:45:00",
        projectId: insertedProjects[0].id,
      },
      {
        description: "paint wood cuts",
        createdAt: "2023-07-12 17:45:00",
        projectId: insertedProjects[0].id,
      },
      {
        description: "timber for art frame",
        type: "material",
        createdAt: "2023-07-12 17:00:00",
        projectId: insertedProjects[1].id,
      },
      {
        description: "buy fabric",
        projectId: insertedProjects[1].id,
        createdAt: "2023-07-12 17:00:00",
        completedAt: "2023-07-14 14:45:34",
        isCompleted: 1,
      },
      {
        description: "decide on motif",
        projectId: insertedProjects[1].id,
        createdAt: "2023-07-12 17:00:00",
        completedAt: "2023-07-14 08:45:34",
        isCompleted: 1,
      },
      {
        description: "cut fabric",
        createdAt: "2023-07-12 17:00:00",
        projectId: insertedProjects[1].id,
      },
    ])
    .returning()
    .all();
};

createProjectsWithTasks();
